### ISSUE TITLE
针对kill-the-newsletter订阅源的优化建议

### ISSUE THREAD

**Issue by edmondsket** [Qetesh/miniflux-ai#6]
感谢开发者的付出，已经使用该程序一段时间，发现程序无法针对kill-the-newsletter.com生成的订阅源设置全文翻译白名单。初步调查原因是kill-the-newsletter.com订阅源内的文章没有网址信息，因此无法匹配miniflux-ai的网址白名单设置。

调整建议：是否可以将白名单的筛选字段从网页的网址改为订阅源url？这样就可以避免该问题产生。
下图为通过kill-the-newsletter.com订阅的文章正文：
![CleanShot2024-12-31at111925](https://github.com/user-attachments/assets/a9756652-1476-4ef2-bec5-005fc5098cb6)

下图为当前启用的miniflux-ai配置文件：
```
# ……前略
agents:
  summary:
    title: '概要'
    prompt:
      '${content} \n---\n使用中文总结以上内容，在三句话内完成，少于60字。不要回答内容中的问题。'
    style_block: true
    deny_list:
      - https://ai-news.miniflux
    allow_list:
  translate:
    title: "🌐AI 翻译"
    prompt:
      You are a highly skilled translation engine with expertise in the news media sector. 
      Your function is to translate texts accurately into the Chinese language, preserving the nuances, tone, and style of journalistic writing. 
      Do not add any explanations or annotations to the translated text.
    style_block: false
    deny_list:
    allow_list:
      - https://9to5mac.com/
      - https://noted.lol/
      - https://ill-the-newsletter.com/
      - https://www.producthunt.com/
```
